# Generated by Django 4.0.4 on 2022-04-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='entregable',
            options={'verbose_name': 'entregable', 'verbose_name_plural': 'entregables'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'estudiante', 'verbose_name_plural': 'estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'profesor', 'verbose_name_plural': 'profesores'},
        ),
    ]
