# Generated by Django 4.0.4 on 2022-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_curso_options_alter_entregable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default=0),
        ),
    ]
